### PR TITLE
Initial pass of re-branding to fair-identifiers-client.

### PR DESCRIPTION
**Pull request by mikedarcy**

### CODE REVIEW

**Review by NickolausDS — COMMENTED** [review]
At a quick glance, everything looks good to me!

A couple other things we could consider is changing the spec for a little more brevity. 

    from fair_identifiers_client.identifiers_api import identifiers_client

Seems a little repetitive. We could condense `identifiers_api` into just `api`, resulting in:

    from fair_identifiers_client.api import identifiers_client

Same with the script name. `fair-identifiers-client` could simply be `fairid`, resulting in `fairid create-identifier --identifier hdl:20.500.12582/7EIFTcs2IXBr`. Not sure how often we will be using that if the idea is to have other sub-clients like Minid wrap this client. If we don't expect many others to use this client directly, it probably isn't a significant worry.

**Comment by mikedarcy** [comment]
I'm not opposed. 

Can we merge now since we pretty much have functional parity and then do other refactoring later?

**Comment by NickolausDS** [comment]
It's probably a good time to add massive breaking changes before folks start using it. If neither of us get to those, I'm still happy using it as-is. The login changes were a good one. I'm still not sure how I feel about how the CLI restructures ArgumentParser as a command decorator. If we add a bunch more features, I could see maintaining that as more trouble than simply switching to something like Click.

**Comment by NickolausDS** [comment]
I don't have write access, but I'd happily hit merge now if I did.

**Pull request merged**
